//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABSDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ABSEntities : DbContext
    {
        public ABSEntities()
            : base("name=ABSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<CustomerDetail> CustomerDetails { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Purpose> Purposes { get; set; }
        public virtual DbSet<Source> Sources { get; set; }
        public virtual DbSet<Venue> Venues { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
    }
}
