//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingID { get; set; }
        public string BookingRef { get; set; }
        public string OfficeRef { get; set; }
        public System.DateTime DateOfBooking { get; set; }
        public string Source { get; set; }
        public string Venue { get; set; }
        public string PurposeOfEvent { get; set; }
        public string PartyName { get; set; }
        public string GroupOrganiser { get; set; }
        public int GroupSize { get; set; }
        public string BookinStatus { get; set; }
        public string BookingSummary { get; set; }
        public string DaySheetNotes { get; set; }
        public string InternalOfficeNotes { get; set; }
        public bool SendEmail { get; set; }
        public bool SendText { get; set; }
    }
}
