//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public int Hoteld { get; set; }
        public string HotelName { get; set; }
        public string CheckIn { get; set; }
        public string CheckOut { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string TownCity { get; set; }
        public string PostCode { get; set; }
        public Nullable<decimal> SingleRoomTariff { get; set; }
        public Nullable<decimal> DoubleRoomTariff { get; set; }
        public Nullable<decimal> TwinRoomTariff { get; set; }
        public Nullable<decimal> TripleRoomTariff { get; set; }
    }
}
